'use strict';

const crypto = require('node:crypto');
const fs = require('node:fs/promises');
const path = require('node:path');
const frontMatter = require('hexo-front-matter');

const MANIFEST_VERSION = 1;
const DEFAULT_NOTE_DIR = path.resolve(__dirname, '../../Note');
const DEFAULT_POSTS_DIR = path.resolve(__dirname, '../source/_posts/note');
const DEFAULT_MANIFEST = path.resolve(__dirname, '../.note-sync-manifest.json');
const GENERATED_MARKER = '<!-- Generated by npm run sync:notes. Edit the source file in Note instead. -->';

function toPosix(value) {
    return value.split(path.sep).join('/');
}

function encodeUrlPath(value) {
    return toPosix(value).split('/').map(segment => encodeURIComponent(segment)).join('/');
}

function hash(value) {
    return crypto.createHash('sha256').update(value).digest('hex');
}

async function exists(target) {
    try {
        await fs.access(target);
        return true;
    } catch {
        return false;
    }
}

function isInside(parent, target) {
    const relative = path.relative(parent, target);
    return relative !== '' && !relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative);
}

function assertInside(parent, target, label) {
    if (!isInside(parent, target)) {
        throw new Error(`${label} is outside the managed directory: ${target}`);
    }
}

async function listFiles(root) {
    if (!await exists(root)) {
        return [];
    }

    const files = [];
    const entries = await fs.readdir(root, { withFileTypes: true });

    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name, 'zh-CN'))) {
        const target = path.join(root, entry.name);
        if (entry.isDirectory()) {
            files.push(...await listFiles(target));
        } else if (entry.isFile()) {
            files.push(target);
        }
    }

    return files;
}

async function listMarkdown(root) {
    const results = [];

    async function visit(directory) {
        const entries = await fs.readdir(directory, { withFileTypes: true });

        for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name, 'zh-CN'))) {
            if (entry.name.startsWith('.') || entry.name === 'node_modules') {
                continue;
            }

            const target = path.join(directory, entry.name);
            if (entry.isDirectory()) {
                await visit(target);
            } else if (entry.isFile() && path.extname(entry.name).toLowerCase() === '.md') {
                results.push(target);
            }
        }
    }

    await visit(root);
    return results;
}

async function hashDirectory(root) {
    if (!await exists(root)) {
        return null;
    }

    const digest = crypto.createHash('sha256');
    for (const file of await listFiles(root)) {
        digest.update(toPosix(path.relative(root, file)));
        digest.update('\0');
        digest.update(await fs.readFile(file));
        digest.update('\0');
    }

    return digest.digest('hex');
}

function rewriteAssetReferences(content, articleName, publicAssetBase) {
    const assetPrefix = `.assets/${articleName}/`;
    return String(content || '')
        .split(`./${assetPrefix}`).join(publicAssetBase)
        .split(assetPrefix).join(publicAssetBase);
}

function isRemoteAsset(value) {
    return /^(?:https?:)?\/\//i.test(value) || /^(?:data|mailto):/i.test(value);
}

function buildPost(source, sourceRelative) {
    const opening = source.match(/^---\s*\r?\n/);
    if (!opening) {
        return null;
    }

    const remainder = source.slice(opening[0].length);
    const closingIndex = remainder.search(/^---\s*$/m);
    if (closingIndex === -1 || !/(?:^|\n)publish\s*:/m.test(remainder.slice(0, closingIndex))) {
        return null;
    }

    let parsed;
    try {
        parsed = frontMatter.parse(source);
    } catch (error) {
        throw new Error(`${sourceRelative}: invalid front matter (${error.message})`);
    }
    if (parsed.publish !== true) {
        return null;
    }

    if (!parsed.date) {
        throw new Error(`${sourceRelative}: published articles must define a date`);
    }

    const extension = path.extname(sourceRelative);
    const articleName = path.basename(sourceRelative, extension);
    const relativeDirectory = path.dirname(sourceRelative) === '.' ? '' : path.dirname(sourceRelative);
    const localAssetPrefix = `.assets/${articleName}/`;
    const bodyAssetBase = '';
    const coverAssetBase = bodyAssetBase;
    const usesLocalAssets = String(parsed._content || '').includes(localAssetPrefix)
        || String(parsed._content || '').includes(`./${localAssetPrefix}`)
        || String(parsed.cover || '').includes(localAssetPrefix);
    const body = rewriteAssetReferences(parsed._content, articleName, bodyAssetBase);
    let cover = parsed.cover;

    if (cover && !isRemoteAsset(String(cover)) && !String(cover).startsWith('/')) {
        const normalizedCover = String(cover).replace(/^\.\//, '');
        if (!normalizedCover.startsWith(localAssetPrefix)) {
            throw new Error(`${sourceRelative}: local cover must be stored in .assets/${articleName}/`);
        }
        cover = rewriteAssetReferences(String(cover), articleName, coverAssetBase);
    }

    const categories = parsed.categories && parsed.categories.length
        ? parsed.categories
        : relativeDirectory.split(path.sep).filter(Boolean);
    const output = {
        title: parsed.title || articleName,
        date: parsed.date,
        categories,
        tags: parsed.tags || [],
        toc: parsed.toc === undefined ? true : parsed.toc
    };

    if (parsed.summary) {
        output.summary = parsed.summary;
    }
    if (cover) {
        output.cover = cover;
    }

    const reserved = new Set(['_content', 'publish', 'title', 'date', 'categories', 'tags', 'toc', 'summary', 'cover']);
    for (const [key, value] of Object.entries(parsed)) {
        if (!reserved.has(key)) {
            output[key] = value;
        }
    }

    output.note_source = toPosix(sourceRelative);
    output._content = `${GENERATED_MARKER}\n\n${body.replace(/^\s+/, '')}`;

    return {
        articleName,
        relativeDirectory,
        usesLocalAssets,
        content: `---\n${frontMatter.stringify({ ...output })}`
    };
}

async function readManifest(manifestFile) {
    if (!await exists(manifestFile)) {
        return { version: MANIFEST_VERSION, entries: {} };
    }

    const manifest = JSON.parse(await fs.readFile(manifestFile, 'utf8'));
    if (manifest.version !== MANIFEST_VERSION || !manifest.entries || typeof manifest.entries !== 'object') {
        throw new Error(`Unsupported note sync manifest: ${manifestFile}`);
    }
    return manifest;
}

async function assertUnmodified(file, expectedHash, force, label) {
    if (force || !expectedHash || !await exists(file)) {
        return;
    }

    const actualHash = hash(await fs.readFile(file));
    if (actualHash !== expectedHash) {
        throw new Error(`${label} was modified in Think. Edit Note instead, or rerun with --force: ${file}`);
    }
}

async function assertDirectoryUnmodified(directory, expectedHash, force, label) {
    if (force || !expectedHash || !await exists(directory)) {
        return;
    }

    if (await hashDirectory(directory) !== expectedHash) {
        throw new Error(`${label} were modified in Think. Edit Note instead, or rerun with --force: ${directory}`);
    }
}

async function syncNotes(options = {}) {
    const projectRoot = options.projectRoot || path.resolve(__dirname, '..');
    const noteDir = path.resolve(options.noteDir || DEFAULT_NOTE_DIR);
    const postsDir = path.resolve(options.postsDir || DEFAULT_POSTS_DIR);
    const manifestFile = path.resolve(options.manifestFile || DEFAULT_MANIFEST);
    const dryRun = Boolean(options.dryRun);
    const force = Boolean(options.force);

    if (!await exists(noteDir)) {
        throw new Error(`Note repository not found: ${noteDir}`);
    }

    const previousManifest = await readManifest(manifestFile);
    const nextManifest = { version: MANIFEST_VERSION, entries: {} };
    const plans = [];
    const destinations = new Set();

    for (const sourceFile of await listMarkdown(noteDir)) {
        const sourceRelative = path.relative(noteDir, sourceFile);
        const source = await fs.readFile(sourceFile, 'utf8');
        const post = buildPost(source, sourceRelative);
        if (!post) {
            continue;
        }

        const postRelative = toPosix(sourceRelative);
        const destinationPost = path.join(postsDir, sourceRelative);
        const sourceAssets = path.join(path.dirname(sourceFile), '.assets', post.articleName);
        const destinationAssets = path.join(postsDir, post.relativeDirectory, post.articleName);
        const contentHash = hash(post.content);
        const assetHash = await hashDirectory(sourceAssets);
        const previous = previousManifest.entries[postRelative];

        assertInside(postsDir, destinationPost, 'Post destination');
        assertInside(postsDir, destinationAssets, 'Asset destination');
        if (destinations.has(destinationPost)) {
            throw new Error(`Multiple Note articles map to the same destination: ${destinationPost}`);
        }
        destinations.add(destinationPost);

        if (!previous && await exists(destinationPost) && !force) {
            throw new Error(`Refusing to overwrite an unmanaged Think article: ${destinationPost}`);
        }
        if (previous) {
            await assertUnmodified(destinationPost, previous.contentHash, force, 'Generated article');
            if (previous.assets) {
                const previousAssets = path.resolve(projectRoot, previous.assets);
                const previousAssetsRoot = previous.assets.startsWith('source/img/note/')
                    ? path.resolve(projectRoot, 'source/img/note')
                    : postsDir;
                assertInside(previousAssetsRoot, previousAssets, 'Previous assets');
                await assertDirectoryUnmodified(previousAssets, previous.assetHash, force, 'Generated assets');
            }
        }

        if (post.usesLocalAssets && assetHash === null) {
            throw new Error(`${postRelative}: references local assets, but .assets/${post.articleName}/ does not exist`);
        }

        const entry = {
            post: toPosix(path.relative(projectRoot, destinationPost)),
            contentHash,
            assets: assetHash === null ? null : toPosix(path.relative(projectRoot, destinationAssets)),
            assetHash
        };
        nextManifest.entries[postRelative] = entry;
        plans.push({ sourceRelative: postRelative, destinationPost, destinationAssets, sourceAssets, content: post.content, entry, previous });
    }

    const stale = Object.entries(previousManifest.entries)
        .filter(([sourceRelative]) => !nextManifest.entries[sourceRelative])
        .map(([sourceRelative, entry]) => ({ sourceRelative, entry }));

    for (const item of stale) {
        const stalePost = path.resolve(projectRoot, item.entry.post);
        assertInside(postsDir, stalePost, 'Stale post');
        await assertUnmodified(stalePost, item.entry.contentHash, force, 'Stale generated article');
        if (item.entry.assets) {
            const staleAssets = path.resolve(projectRoot, item.entry.assets);
            const staleAssetsRoot = item.entry.assets.startsWith('source/img/note/')
                ? path.resolve(projectRoot, 'source/img/note')
                : postsDir;
            assertInside(staleAssetsRoot, staleAssets, 'Stale assets');
            await assertDirectoryUnmodified(staleAssets, item.entry.assetHash, force, 'Stale generated assets');
        }
    }

    let changed = stale.length > 0;
    for (const plan of plans) {
        const postChanged = !await exists(plan.destinationPost)
            || hash(await fs.readFile(plan.destinationPost)) !== plan.entry.contentHash;
        const assetsChanged = plan.entry.assetHash !== null && (
            !await exists(plan.destinationAssets)
            || await hashDirectory(plan.destinationAssets) !== plan.entry.assetHash
        );
        const removedAssets = plan.entry.assetHash === null && plan.previous && plan.previous.assets;
        const previousAssets = plan.previous && plan.previous.assets
            ? path.resolve(projectRoot, plan.previous.assets)
            : null;
        const movedAssets = previousAssets && previousAssets !== plan.destinationAssets;
        changed ||= postChanged || assetsChanged || Boolean(removedAssets) || Boolean(movedAssets);

        if (dryRun) {
            continue;
        }

        if (postChanged) {
            await fs.mkdir(path.dirname(plan.destinationPost), { recursive: true });
            await fs.writeFile(plan.destinationPost, plan.content);
        }
        if (assetsChanged) {
            await fs.rm(plan.destinationAssets, { recursive: true, force: true });
            await fs.mkdir(path.dirname(plan.destinationAssets), { recursive: true });
            await fs.cp(plan.sourceAssets, plan.destinationAssets, { recursive: true });
        } else if (removedAssets) {
            const previousAssetsRoot = plan.previous.assets.startsWith('source/img/note/')
                ? path.resolve(projectRoot, 'source/img/note')
                : postsDir;
            assertInside(previousAssetsRoot, previousAssets, 'Removed assets');
            await fs.rm(previousAssets, { recursive: true, force: true });
        }
        if (movedAssets && await exists(previousAssets)) {
            const previousAssetsRoot = plan.previous.assets.startsWith('source/img/note/')
                ? path.resolve(projectRoot, 'source/img/note')
                : postsDir;
            assertInside(previousAssetsRoot, previousAssets, 'Moved assets');
            await fs.rm(previousAssets, { recursive: true, force: true });
        }
    }

    const serializedManifest = `${JSON.stringify(nextManifest, null, 2)}\n`;
    const manifestChanged = !await exists(manifestFile)
        || await fs.readFile(manifestFile, 'utf8') !== serializedManifest;
    changed ||= manifestChanged;

    if (!dryRun) {
        for (const item of stale) {
            await fs.rm(path.resolve(projectRoot, item.entry.post), { force: true });
            if (item.entry.assets) {
                await fs.rm(path.resolve(projectRoot, item.entry.assets), { recursive: true, force: true });
            }
        }

        if (manifestChanged) {
            await fs.writeFile(`${manifestFile}.tmp`, serializedManifest);
            await fs.rename(`${manifestFile}.tmp`, manifestFile);
        }
    }

    return {
        published: plans.length,
        removed: stale.length,
        changed
    };
}

function parseArguments(argv) {
    const options = {};

    for (let index = 0; index < argv.length; index += 1) {
        const argument = argv[index];
        if (argument === '--note-dir') {
            options.noteDir = argv[++index];
        } else if (argument === '--dry-run') {
            options.dryRun = true;
        } else if (argument === '--check') {
            options.dryRun = true;
            options.check = true;
        } else if (argument === '--force') {
            options.force = true;
        } else if (argument === '--help') {
            options.help = true;
        } else {
            throw new Error(`Unknown argument: ${argument}`);
        }
    }

    if (argv.includes('--note-dir') && !options.noteDir) {
        throw new Error('--note-dir requires a path');
    }
    return options;
}

async function main() {
    const options = parseArguments(process.argv.slice(2));
    if (options.help) {
        process.stdout.write('Usage: npm run sync:notes -- [--note-dir PATH] [--dry-run|--check] [--force]\n');
        return;
    }

    const result = await syncNotes(options);
    process.stdout.write(`Note sync: ${result.published} published, ${result.removed} removed, ${result.changed ? 'changes found' : 'already up to date'}\n`);
    if (options.check && result.changed) {
        process.exitCode = 1;
    }
}

if (require.main === module) {
    main().catch(error => {
        process.stderr.write(`Note sync failed: ${error.message}\n`);
        process.exitCode = 1;
    });
}

if (typeof hexo !== 'undefined') {
    hexo.extend.filter.register('before_post_render', data => {
        if (data.note_source && data.cover && !isRemoteAsset(String(data.cover)) && !String(data.cover).startsWith('/')) {
            data.cover = `/${toPosix(data.path)}${encodeUrlPath(String(data.cover))}`;
        }
        return data;
    });
}

module.exports = {
    GENERATED_MARKER,
    buildPost,
    parseArguments,
    rewriteAssetReferences,
    syncNotes
};
